In [1]:
import pandas as pd
import numpy as np

data = {
    "Order_ID": range(1001, 1016),
    "Customer_Name": [
        " Anas ", "Rahul", "Priya ", "Kumar", "Divya",
        "Arun", "Sneha", "Vijay", " Meena", "Ravi",
        "John", "Kavya", "Ajay", "Sara", "Manoj"
    ],
    "City": [
        "Chennai", "chennai", " CHENNAI ", "Madurai", "madurai",
        "Coimbatore", "COIMBATORE", "Chennai", "Madurai", None,
        "Chennai", "Trichy", " trichy ", "Coimbatore", "Chennai"
    ],
    "Product": [
        "Laptop", "Mobile", "Tablet", "Laptop", "Mobile",
        "Tablet", "Laptop", "Mobile", "Tablet", "Laptop",
        "Mobile", "Laptop", "Tablet", "Mobile", "Laptop"
    ],
    "Quantity": [
        2, 1, 3, 2, None, 1, 2, 1, 4, 2, 1, 3, 2, 1, 100
    ],
    "Price": [
        "50000", "15000", "12000", "52000", "18000",
        "invalid", "51000", "16000", "12500", "49000",
        "17000", "53000", "11000", "16000", "50000"
    ],
    "Order_Date": [
        "2026-01-05", "05/01/2026", "2026-01-07", "10-01-2026",
        "2026/01/12", "15/01/2026", "2026-01-18", "20-01-2026",
        None, "2026/01/22", "25/01/2026", "2026-01-27",
        "30-01-2026", "2026/02/02", "2026-02-05"
    ],
    "Rating": [
        4.5, 4.0, 5.0, 4.2, 3.8, 4.0, 4.7, None,
        3.5, 4.1, 4.0, 4.8, 3.9, 4.3, 5.0
    ]
}

df = pd.DataFrame(data)

print(df)

    Order_ID Customer_Name        City Product  Quantity    Price  Order_Date  \
0       1001         Anas      Chennai  Laptop       2.0    50000  2026-01-05
1       1002         Rahul     chennai  Mobile       1.0    15000  05/01/2026
2       1003        Priya     CHENNAI   Tablet       3.0    12000  2026-01-07
3       1004         Kumar     Madurai  Laptop       2.0    52000  10-01-2026
4       1005         Divya     madurai  Mobile       NaN    18000  2026/01/12
5       1006          Arun  Coimbatore  Tablet       1.0  invalid  15/01/2026
6       1007         Sneha  COIMBATORE  Laptop       2.0    51000  2026-01-18
7       1008         Vijay     Chennai  Mobile       1.0    16000  20-01-2026
8       1009         Meena     Madurai  Tablet       4.0    12500         NaN
9       1010          Ravi         NaN  Laptop       2.0    49000  2026/01/22
10      1011          John     Chennai  Mobile       1.0    17000  25/01/2026
11      1012         Kavya      Trichy  Laptop       3.0    53000  2026-01-27
12      1013          Ajay     trichy   Tablet       2.0    11000  30-01-2026
13      1014          Sara  Coimbatore  Mobile       1.0    16000  2026/02/02
14      1015         Manoj     Chennai  Laptop     100.0    50000  2026-02-05

    Rating
0      4.5
1      4.0
2      5.0
3      4.2
4      3.8
5      4.0
6      4.7
7      NaN
8      3.5
9      4.1
10     4.0
11     4.8
12     3.9
13     4.3
14     5.0

In [2]:
#Statistical Analysis

print(df.isnull())
print(df.isna())
print(df.isnull().sum())
print(df.isna().sum().sum())

df_dropna = df.dropna()
print(df_dropna)

    Order_ID  Customer_Name   City  Product  Quantity  Price  Order_Date  \
0      False          False  False    False     False  False       False
1      False          False  False    False     False  False       False
2      False          False  False    False     False  False       False
3      False          False  False    False     False  False       False
4      False          False  False    False      True  False       False
5      False          False  False    False     False  False       False
6      False          False  False    False     False  False       False
7      False          False  False    False     False  False       False
8      False          False  False    False     False  False        True
9      False          False   True    False     False  False       False
10     False          False  False    False     False  False       False
11     False          False  False    False     False  False       False
12     False          False  False    False     False  False       False
13     False          False  False    False     False  False       False
14     False          False  False    False     False  False       False

    Rating
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
10   False
11   False
12   False
13   False
14   False
    Order_ID  Customer_Name   City  Product  Quantity  Price  Order_Date  \
0      False          False  False    False     False  False       False
1      False          False  False    False     False  False       False
2      False          False  False    False     False  False       False
3      False          False  False    False     False  False       False
4      False          False  False    False      True  False       False
5      False          False  False    False     False  False       False
6      False          False  False    False     False  False       False
7      False          False  False    False     False  False       False
8      False          False  False    False     False  False        True
9      False          False   True    False     False  False       False
10     False          False  False    False     False  False       False
11     False          False  False    False     False  False       False
12     False          False  False    False     False  False       False
13     False          False  False    False     False  False       False
14     False          False  False    False     False  False       False

    Rating
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
10   False
11   False
12   False
13   False
14   False
Order_ID         0
Customer_Name    0
City             1
Product          0
Quantity         1
Price            0
Order_Date       1
Rating           1
dtype: int64
4
    Order_ID Customer_Name        City Product  Quantity    Price  Order_Date  \
0       1001         Anas      Chennai  Laptop       2.0    50000  2026-01-05
1       1002         Rahul     chennai  Mobile       1.0    15000  05/01/2026
2       1003        Priya     CHENNAI   Tablet       3.0    12000  2026-01-07
3       1004         Kumar     Madurai  Laptop       2.0    52000  10-01-2026
5       1006          Arun  Coimbatore  Tablet       1.0  invalid  15/01/2026
6       1007         Sneha  COIMBATORE  Laptop       2.0    51000  2026-01-18
10      1011          John     Chennai  Mobile       1.0    17000  25/01/2026
11      1012         Kavya      Trichy  Laptop       3.0    53000  2026-01-27
12      1013          Ajay     trichy   Tablet       2.0    11000  30-01-2026
13      1014          Sara  Coimbatore  Mobile       1.0    16000  2026/02/02
14      1015         Manoj     Chennai  Laptop     100.0    50000  2026-02-05

    Rating
0      4.5
1      4.0
2      5.0
3      4.2
5      4.0
6      4.7
10     4.0
11     4.8
12     3.9
13     4.3
14     5.0

In [4]:
#Identify and Handle Missing Values
clean_df = df.copy()

clean_df["City"] = clean_df["City"].fillna("Unknown")
clean_df["Quantity"] = clean_df["Quantity"].fillna(
    clean_df["Quantity"].median()
)
clean_df["Rating"] = clean_df["Rating"].fillna(
    clean_df["Rating"].median()
)

In [5]:
price_before = pd.to_numeric(df["Price"], errors="coerce")

print("Total Quantity:", df["Quantity"].sum())
print("Average Quantity:", df["Quantity"].mean())
print("Median Quantity:", df["Quantity"].median())

print("Average Price:", price_before.mean())
print("Median Price:", price_before.median())

print(df[["Quantity", "Rating"]].describe())

Total Quantity: 125.0
Average Quantity: 8.928571428571429
Median Quantity: 2.0
Average Price: 30178.571428571428
Median Price: 17500.0
         Quantity     Rating
count   14.000000  14.000000
mean     8.928571   4.271429
std     26.228183   0.463147
min      1.000000   3.500000
25%      1.000000   4.000000
50%      2.000000   4.150000
75%      2.750000   4.650000
max    100.000000   5.000000

In [6]:
#Data Formatting and Standardization
clean_df["Customer_Name"] = clean_df["Customer_Name"].str.strip()
clean_df["City"] = clean_df["City"].str.strip()

clean_df["Customer_Name"] = clean_df["Customer_Name"].str.title()
clean_df["City"] = clean_df["City"].str.title()
clean_df["Product"] = clean_df["Product"].str.title()

clean_df["Price"] = pd.to_numeric(
    clean_df["Price"], errors="coerce"
)

clean_df["Order_Date"] = pd.to_datetime(
    clean_df["Order_Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

print(clean_df)

    Order_ID Customer_Name        City Product  Quantity    Price Order_Date  \
0       1001          Anas     Chennai  Laptop       2.0  50000.0 2026-05-01
1       1002         Rahul     Chennai  Mobile       1.0  15000.0 2026-01-05
2       1003         Priya     Chennai  Tablet       3.0  12000.0 2026-07-01
3       1004         Kumar     Madurai  Laptop       2.0  52000.0 2026-01-10
4       1005         Divya     Madurai  Mobile       2.0  18000.0 2026-12-01
5       1006          Arun  Coimbatore  Tablet       1.0      NaN 2026-01-15
6       1007         Sneha  Coimbatore  Laptop       2.0  51000.0 2026-01-18
7       1008         Vijay     Chennai  Mobile       1.0  16000.0 2026-01-20
8       1009         Meena     Madurai  Tablet       4.0  12500.0        NaT
9       1010          Ravi     Unknown  Laptop       2.0  49000.0 2026-01-22
10      1011          John     Chennai  Mobile       1.0  17000.0 2026-01-25
11      1012         Kavya      Trichy  Laptop       3.0  53000.0 2026-01-27
12      1013          Ajay      Trichy  Tablet       2.0  11000.0 2026-01-30
13      1014          Sara  Coimbatore  Mobile       1.0  16000.0 2026-02-02
14      1015         Manoj     Chennai  Laptop     100.0  50000.0 2026-05-02

    Rating
0     4.50
1     4.00
2     5.00
3     4.20
4     3.80
5     4.00
6     4.70
7     4.15
8     3.50
9     4.10
10    4.00
11    4.80
12    3.90
13    4.30
14    5.00

In [7]:
#Data Type Conversion
print(df.dtypes)
df.info()

clean_df["Order_ID"] = clean_df["Order_ID"].astype("int64")

clean_df["Quantity"] = clean_df["Quantity"].round().astype("Int64")

clean_df["Price"] = pd.to_numeric(
    clean_df["Price"], errors="coerce"
)

clean_df["Rating"] = pd.to_numeric(
    clean_df["Rating"], errors="coerce"
)

print(clean_df.dtypes)
clean_df.info()

Order_ID           int64
Customer_Name        str
City                 str
Product              str
Quantity         float64
Price                str
Order_Date           str
Rating           float64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       15 non-null     int64
 1   Customer_Name  15 non-null     str
 2   City           14 non-null     str
 3   Product        15 non-null     str
 4   Quantity       14 non-null     float64
 5   Price          15 non-null     str
 6   Order_Date     14 non-null     str
 7   Rating         14 non-null     float64
dtypes: float64(2), int64(1), str(5)
memory usage: 1.1 KB
Order_ID                  int64
Customer_Name               str
City                        str
Product                     str
Quantity                  Int64
Price                   float64
Order_Date       datetime64[us]
Rating                  float64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       15 non-null     int64
 1   Customer_Name  15 non-null     str
 2   City           15 non-null     str
 3   Product        15 non-null     str
 4   Quantity       15 non-null     Int64
 5   Price          14 non-null     float64
 6   Order_Date     14 non-null     datetime64[us]
 7   Rating         15 non-null     float64
dtypes: Int64(1), datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 1.1 KB

In [8]:
#Identify Outliers Using IQR
print(clean_df[["Quantity", "Price"]].describe())

Q1 = clean_df["Quantity"].quantile(0.25)
Q3 = clean_df["Quantity"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

outliers = clean_df[
    (clean_df["Quantity"] < lower_bound) |
    (clean_df["Quantity"] > upper_bound)
]

print(outliers)

        Quantity         Price
count       15.0     14.000000
mean    8.466667  30178.571429
std    25.337343  18679.078324
min          1.0  11000.000000
25%          1.0  15250.000000
50%          2.0  17500.000000
75%          2.5  50000.000000
max        100.0  53000.000000
Q1: 1.0
Q3: 2.5
IQR: 1.5
Lower Bound: -1.25
Upper Bound: 4.75
    Order_ID Customer_Name     City Product  Quantity    Price Order_Date  \
14      1015         Manoj  Chennai  Laptop       100  50000.0 2026-05-02

    Rating
14     5.0

In [9]:
#Handle Outliers
before_outlier_handling = clean_df.copy()

clean_df.loc[
    clean_df["Order_ID"] == 1015, "Quantity"
] = 10

print(before_outlier_handling[
    before_outlier_handling["Order_ID"] == 1015
])

print(clean_df[
    clean_df["Order_ID"] == 1015
])

    Order_ID Customer_Name     City Product  Quantity    Price Order_Date  \
14      1015         Manoj  Chennai  Laptop       100  50000.0 2026-05-02

    Rating
14     5.0
    Order_ID Customer_Name     City Product  Quantity    Price Order_Date  \
14      1015         Manoj  Chennai  Laptop        10  50000.0 2026-05-02

    Rating
14     5.0

In [10]:
#Verify and Compare Results
clean_df = clean_df.drop_duplicates(subset=["Order_ID"])

print("Original Row Count:", len(df))
print("Cleaned Row Count:", len(clean_df))

print("Original Missing Values:")
print(df.isna().sum())

print("Cleaned Missing Values:")
print(clean_df.isna().sum())

print("Original Quantity Statistics:")
print(df["Quantity"].describe())

print("Cleaned Quantity Statistics:")
print(clean_df["Quantity"].describe())

print("Original Price Statistics:")
print(pd.to_numeric(df["Price"], errors="coerce").describe())

print("Cleaned Price Statistics:")
print(clean_df["Price"].describe())

display(df)
display(clean_df)

Original Row Count: 15
Cleaned Row Count: 15
Original Missing Values:
Order_ID         0
Customer_Name    0
City             1
Product          0
Quantity         1
Price            0
Order_Date       1
Rating           1
dtype: int64
Cleaned Missing Values:
Order_ID         0
Customer_Name    0
City             0
Product          0
Quantity         0
Price            1
Order_Date       1
Rating           0
dtype: int64
Original Quantity Statistics:
count     14.000000
mean       8.928571
std       26.228183
min        1.000000
25%        1.000000
50%        2.000000
75%        2.750000
max      100.000000
Name: Quantity, dtype: float64
Cleaned Quantity Statistics:
count        15.0
mean     2.466667
std      2.263583
min           1.0
25%           1.0
50%           2.0
75%           2.5
max          10.0
Name: Quantity, dtype: Float64
Original Price Statistics:
count       14.000000
mean     30178.571429
std      18679.078324
min      11000.000000
25%      15250.000000
50%      17500.000000
75%      50000.000000
max      53000.000000
Name: Price, dtype: float64
Cleaned Price Statistics:
count       14.000000
mean     30178.571429
std      18679.078324
min      11000.000000
25%      15250.000000
50%      17500.000000
75%      50000.000000
max      53000.000000
Name: Price, dtype: float64

,Order_ID,Customer_Name,City,Product,Quantity,Price,Order_Date,Rating
0,1001,Anas,Chennai,Laptop,2.0,50000,2026-01-05,4.5
1,1002,Rahul,chennai,Mobile,1.0,15000,05/01/2026,4.0
2,1003,Priya,CHENNAI,Tablet,3.0,12000,2026-01-07,5.0
3,1004,Kumar,Madurai,Laptop,2.0,52000,10-01-2026,4.2
4,1005,Divya,madurai,Mobile,NaN,18000,2026/01/12,3.8
5,1006,Arun,Coimbatore,Tablet,1.0,invalid,15/01/2026,4.0
6,1007,Sneha,COIMBATORE,Laptop,2.0,51000,2026-01-18,4.7
7,1008,Vijay,Chennai,Mobile,1.0,16000,20-01-2026,NaN
8,1009,Meena,Madurai,Tablet,4.0,12500,NaN,3.5
9,1010,Ravi,NaN,Laptop,2.0,49000,2026/01/22,4.1
10,1011,John,Chennai,Mobile,1.0,17000,25/01/2026,4.0
11,1012,Kavya,Trichy,Laptop,3.0,53000,2026-01-27,4.8
12,1013,Ajay,trichy,Tablet,2.0,11000,30-01-2026,3.9
13,1014,Sara,Coimbatore,Mobile,1.0,16000,2026/02/02,4.3
14,1015,Manoj,Chennai,Laptop,100.0,50000,2026-02-05,5.0

,Order_ID,Customer_Name,City,Product,Quantity,Price,Order_Date,Rating
0,1001,Anas,Chennai,Laptop,2,50000.0,2026-05-01,4.50
1,1002,Rahul,Chennai,Mobile,1,15000.0,2026-01-05,4.00
2,1003,Priya,Chennai,Tablet,3,12000.0,2026-07-01,5.00
3,1004,Kumar,Madurai,Laptop,2,52000.0,2026-01-10,4.20
4,1005,Divya,Madurai,Mobile,2,18000.0,2026-12-01,3.80
5,1006,Arun,Coimbatore,Tablet,1,NaN,2026-01-15,4.00
6,1007,Sneha,Coimbatore,Laptop,2,51000.0,2026-01-18,4.70
7,1008,Vijay,Chennai,Mobile,1,16000.0,2026-01-20,4.15
8,1009,Meena,Madurai,Tablet,4,12500.0,NaT,3.50
9,1010,Ravi,Unknown,Laptop,2,49000.0,2026-01-22,4.10
10,1011,John,Chennai,Mobile,1,17000.0,2026-01-25,4.00
11,1012,Kavya,Trichy,Laptop,3,53000.0,2026-01-27,4.80
12,1013,Ajay,Trichy,Tablet,2,11000.0,2026-01-30,3.90
13,1014,Sara,Coimbatore,Mobile,1,16000.0,2026-02-02,4.30
14,1015,Manoj,Chennai,Laptop,10,50000.0,2026-05-02,5.00

In [11]:
#Compare Statistics Before and After Cleaning
comparison = pd.DataFrame({
    "Measure": [
        "Total Quantity",
        "Mean Quantity",
        "Median Quantity",
        "Mean Price",
        "Median Price"
    ],
    "Before Cleaning": [
        df["Quantity"].sum(),
        df["Quantity"].mean(),
        df["Quantity"].median(),
        pd.to_numeric(df["Price"], errors="coerce").mean(),
        pd.to_numeric(df["Price"], errors="coerce").median()
    ],
    "After Cleaning": [
        clean_df["Quantity"].sum(),
        clean_df["Quantity"].mean(),
        clean_df["Quantity"].median(),
        clean_df["Price"].mean(),
        clean_df["Price"].median()
    ]
})

print(comparison.round(2))

           Measure  Before Cleaning  After Cleaning
0   Total Quantity           125.00           37.00
1    Mean Quantity             8.93            2.47
2  Median Quantity             2.00            2.00
3       Mean Price         30178.57        30178.57
4     Median Price         17500.00        17500.00

In [12]:
#Sales Analysis
clean_df["Sales"] = clean_df["Quantity"] * clean_df["Price"]

sales_summary = clean_df.groupby(
    ["City", "Product"], dropna=False
)["Sales"].sum().reset_index()

print(sales_summary)

          City Product     Sales
0      Chennai  Laptop  600000.0
1      Chennai  Mobile   48000.0
2      Chennai  Tablet   36000.0
3   Coimbatore  Laptop  102000.0
4   Coimbatore  Mobile   16000.0
5   Coimbatore  Tablet       0.0
6      Madurai  Laptop  104000.0
7      Madurai  Mobile   36000.0
8      Madurai  Tablet   50000.0
9       Trichy  Laptop  159000.0
10      Trichy  Tablet   22000.0
11     Unknown  Laptop   98000.0